- Gopkg.lock
- README.md
- main.go
Added the ability to include a `.tfswitchrc` file within a repo to have tfswitch automatically use the desired Terraform version. 
Similar idea to [nvm](https://github.com/creationix/nvm).
> Added support for a .tfswitchrc file

- README.md
- docs/index.md
I hit the `command not found: add-zsh-hook` error when using `tfswitch` in zsh (v5.6.2).  Searched the web for a bit and realized I needed to load the `add-zsh-hook` function.
> document fix for 'command not found: add-zsh-hook'

- README.md
- main.go
* fixes #60
* treats `.terraform-version` file exactly like the `.tfswitchrc` file
for simplicity's sake and duplicates the if statement so this behavior
can easily be modified later
> Adds support for `.terraform-version` file

- main.go
I'm reluctant to change permissions on the default /usr/local/bin directory to allow tfswitch to work. This means I need to use a custom bin directory. I specified that in my config file using the $HOME environment variable:
```
:~% cat ~/.tfswitch.toml
bin = "$HOME/bin/terraform"
```
but found that tfswitch doesn't expand environment variables. This isn't an issue if I supply it as a command line argument, because the shell expands it. 
This change expands the value found in the config, using the variables defined in current environment, when it's assigned.
> Allow expansion of environment variables in the configuration file

- snapcraft.yaml
> added snapscraft file

- www/docs/Quick-Start.md
Add a snippet to execute tfswitch after a `cd` if a `tf` file with an `required_version` is present. This works only in [fish shell](http://fishshell.com).
I'm not really sure if the project wants to start a snippet collection. Feel free to advise, correct or reject.
> Execute tfswitch after cd in fish shell

- main.go
work similarly for when a .tfswitch.toml is present as when it does not.
Fixes https://github.com/warrensbox/terraform-switcher/issues/120
> Make the precedence of what determines what terraform version to use

- main.go
Lack of line break causes lines to print together
```
❯ tfswitch
Reading required version from terraform fileReading required version from constraint: ~> 0.14.0
Matched version: 0.14.11
Switched terraform to version "0.14.11"
```
> Fix newline formatting issue

- .travis.yml
- README.md
- lib/common_test.go
- lib/download.go
- lib/download_test.go
- lib/files_test.go
- lib/install.go
- lib/symlink_test.go
- main.go
* ♿ changes to make `tfswitch` work on windows;
* before: fails at `rename` unzipped `terraform` binary to `terraform_<version>`, as windows terraform binary is `terraform.exe` (ends with `exe`)
* now: installs `terraform` successfully to `$HOME/bin`, when `$HOME/.tfswitch.toml` is defined (with `bin="<%USERPROFILE%>\\bin\\terraform.exe"`) and `tfswitch` is run under `Administrator` Mode
* ✅ fix process holding `RECENT` file issue in `file_test.go` (`TestWriteLines`/`TestReadLines`) cases, this causes os panic;
* ♻️ refactor code use `filepath.Join` instead of concatenating strings manually, avoid duplicated colde on file path through defining variables to store file path;
* 🚀 add ci (`travis.yaml`) on `windows/osx`
https://user-images.githubusercontent.com/4773348/120096838-fbcdd280-c170- …
> ♿  changes to make tfswitch work on windows, fix some test 🐛 bugs, ♻️ refactor code, add 🚀 ci on `windows/osx`

- README.md
- main.go
This PR implements the --chdir - flag feature.
Since Terraform support this flag it is also nice to have it in TfSwitcher aswell.
> Implement --chdir - Flag

- .goreleaser.yml
Just happened to notice this today. 
The 's' being lowercase instead of uppercase is what caught my eye, but apparently the 'm' is supposed to be lowercase.
> MacOs -> macOS to be consistent with the standard casing

- .circleci/config.yml
- Makefile
- go.mod
Bumping the project to go 1.18
Tested locally and things are functioning still.
> Upgrade to Go 1.18

- .circleci/config.yml
- Makefile
- go.mod
- test-data/test_tfswitchtoml/.tfswitch.toml
Rebase the 0.14 release branch with recent commits to master.
> Rebase over master

- main.go
Closes #222
There's no need to add a prefix in the code because the current path would already be respected by default. In turn, having this prefix breaks absolute paths during execution (i.e. tfswitch -c /some/other/path) as described in #222 and demonstrated below.
Current behavior:
```
$ ./tfswitch -c test-data/test_tfswitchtoml
Reading configuration from current directory for .tfswitch.toml
Switched terraform to version "0.11.3" 
$ ./tfswitch -c $PWD/test-data/test_tfswitchtoml
Use the arrow keys to navigate: ↓ ↑ → ← 
? Select Terraform version: 
▸ 0.11.3 *recent
1.2.1
1.2.0
1.1.9
↓   1.1.8
```
After fixes:
```
$ ./tfswitch -c test-data/test_tfswitchtoml
Reading configuration from current directory for .tfswitch.toml
Switched terraform to version "0.11.3" 
$ ./tfswitch -c …
```
> Fix chDirPath option for absolute paths

- lib/list_versions.go
This fixes https://github.com/warrensbox/terraform-switcher/issues/250 and broken unit tests.
> adjust regex to get all terraform versinos from mirror

- install.sh
- As seen from #260 Linux ARMv{6,7} are missing from `install.sh`
despite binaries are built for these platforms in recent releases, so
add these two to the pool.
> Add Linux ARMv{6,7} arch to `install.sh`

- README.md
- main.go
This flag will allow us to specify a default version to install which will be useful for the CI systems instead of going into the prompt
> Default version flag added

- .circleci/config.yml
- go.mod
Updated the go version to 1.22 (latest) to fix the critical vulnerabilities
> Update the go version to 1.22

- go.mod
golang.org/x/text 0.3.7 version is vulnerable. (HIGH) I did the necessary changes as the latest version (0.7.0)
CVE-2022-32149 --  https://avd.aquasec.com/nvd/cve-2022-32149
> Updating "x/text" to prevent CVE-2022-32149

- lib/install.go
Reopening #294 after changing branch names
> Fix init function

- .github/workflows/build.yml
- .github/workflows/release.yml
fixes #344, fixes #345
relates to #339
> fix: Downgrade GH Ubuntu runner to `20.04`

- .github/workflows/build.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Switch back to `ubuntu-latest` GH runners but build statically linked Go binaries instead
- Confirmed Linux `amd64` binary works on Linux Mint 19.3 Tricia (based on Ubuntu Bionic 18.04)
- No penalty on the size of binaries as of look of it
- While here, brush up and align GH Workflow YAML configs a bit
> feat: Build statically linked binaries

- CHANGELOG.md
- Add changelog entries for each tag starting from the one that already existed in CHANGELOG
- Utilized [chelnak/gh-changelog](https://github.com/chelnak/gh-changelog) to automate process
- Manually adjusted where `gh-changelog` didn't make its job good enough
> docs: Actualize CHANGELOG

- lib/defaults.go
- lib/download_test.go
- lib/files.go
- lib/files_test.go
- lib/install.go
- lib/list_versions_test.go
- lib/symlink_test.go
- main.go
Attempt to hastily fix Fatal level calls to logger by appending `os.Exit(1)` to each `logger.Fatal()` (`logger.Fatalf()`) call, as it appeared that it doesn't exit as we'd expect it to.
Refs:
- #334 (comment)
- gookit/slog#143
> bugfix: Fix Fatal logger calls by force exit

- .github/workflows/release.yml
It seems that the version update only works over the PR way. With this i try to solve that problem.
> Release Workflow fix

- main.go
Version variable must not be initialized to be set during the build process. See https://stackoverflow.com/questions/11354518/application-auto-build-versioning
> Fix for Version during build process

- .goreleaser.yml
See https://github.com/warrensbox/terraform-switcher/pull/359#issuecomment-2068169987
> feat(goreleaser): Update `changelog` section of `.goreleaser.yml`

- README.md
- lib/common.go
- lib/defaults.go
- lib/files.go
- lib/install.go
- lib/list_versions.go
- lib/param_parsing/parameters.go
- lib/symlink.go
- main.go
- www/docs/usage/ci-cd.md
- www/docs/usage/commandline.md
- www/docs/usage/config-files.md
- www/docs/usage/general.md
This change adds a new flag `-i` or `--install` that will allow you to set where the Terraform binary is downloaded/installed into. Useful for edge cases where you need to share commonly installed versions of Terraform. 
This is in draft as it is built upon this PRs that should be merged first. To save headaches with merge conflicts this PR already includes that commit.
- #295 - Thanks @jukie for the PR. 
Once the above PR has been merged ping me and I can update this branch with latest master.
I have created a similar PR for tgswitch here - https://github.com/warrensbox/tgswitch/pull/140
> Feature: Add flag for install location (optional)

- lib/param_parsing/versiontf.go
- lib/param_parsing/versiontf_test.go
- test-data/integration-tests/test_versiontf/version.tf
- test-data/skip-integration-tests/test_versiontf_non_matching_constraints/version.tf
- added fix for #400 when the comparator is not separated from the version number by a space
- possibly fixes #402 as well
> Fix for #400 - Whitespaces and Version Constraints

- install.sh
fixes: #394
fixes: #395
relates: #401
This fixes downloading `v` and no `v` releases after the switch to `v`-prefixed release versions.
This does not fix some historical releases that have no assets or that use capitalized platform names instead of lowercase. This is something that didn't work pre-`v` era too. We can fix this too it there will be a request for that though.
> fix: Adjust `install.sh` for new tagging format

- lib/param_parsing/terragrunt.go
- lib/param_parsing/terragrunt_test.go
- test-data/integration-tests/test_terragrunt_hcl/terragrunt.hcl
This will fix #401 
* removed diagnostic.hasError check as it is expected to have an error every time something is present that we are not looking explicitly for.
* introduced test if a terraform_version_constraint can be found in hcl file.
> Fix terragrunt parsing

- README.md
- www/docs/Continuous-Integration.md
- www/docs/Installation.md
- www/docs/Troubleshoot.md
- www/docs/Upgrade-or-Uninstall.md
- www/docs/usage/config-files.md
Fix links to `install.sh` after moving from `release` to `master` branch as main branch
fixes #431
> docs: Fix links to `install.sh`

- lib/defaults.go
- lib/files.go
- lib/install.go
- lib/products.go
- lib/recent.go
Replace methods for interacting with recent file with two methods:
* get recent versions (which ignores all errors and always returns a list - only populated if the data could be successfully read)
* add recent version, which reads the current versions and prepends to new version to add
Issue #315
> Convert recent file to json

- lib/param_parsing/parameters.go
Fixes #443 
- skip any parsing of config files if the -v flag is provided
> skip any parsing of config files if the -v flag is provided

- lib/logging.go
- lib/param_parsing/parameters.go
- added --log-level=ERROR option to supress all non-error logging.
Likely solves #422
> Added ERRORlog-level

- lib/files.go
- lib/param_parsing/toml.go
* fix: Allow Env vars in TOML `bin` value again
* chore: While was investigating, committed tiny cleanup/improvements in `lib/files.go`
> fix: Allow Env vars in TOML `bin` value (re-introduce feature)

- lib/symlink.go
- lib/symlink_test.go
> fix: Remove duplicate .exe extension added to paths for windows inside symlink, as this is already handled by ConvertExecutableExt

- lib/defaults.go
- lib/param_parsing/parameters.go
Move logic for setting default bin path to parameters, which sets the default once the product is known
Issue #482
> default: Fix default binary symlink name for Opentofu to be tofu.exe, rather than terraform.exe

- .github/labeler.yml
- .github/release.yml
- .github/workflows/multi-labeler.yml
Auto label PRs based on title, commit message, and branch name.
PR labels are used to structure and group [CHANGELOG entries](/CHANGELOG.howto.md) and [auto-generated Release change logs](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes).
Refs:
- https://github.com/fuxingloh/multi-labeler
- https://www.conventionalcommits.org/
- https://github.com/warrensbox/terraform-switcher/labels
> chore: Add Multi Labeler workflow

- lib/symlink.go
fixes #493
OLD:
```
Unable to find existing directory in "/usr/local/bin/terraform or /Users/${CURRENT_USER}/bin/terraform". Manually create one of them and try again.
```
NEW
```
None of the installation directories exist: "/usr/local/bin", "/home/${CURRENT_USER}/bin". Manually create one of them and try again.
```
> fix: Improve wording when installing binary

- lib/list_versions.go
- lib/logging.go
> Split output and logs

- .goreleaser.yml
- CHANGELOG.md
* docs: Update CHANGELOG with `v1.2.3`
* While here update Goreleaser config to match v2: https://goreleaser.com/errors/version/
> docs: Update CHANGELOG with `v1.2.3`

- www/docs/usage/ci-cd.md
- www/docs/usage/config-files.md
- www/docs/usage/general.md
Update documentation by dropping TOML mentions where it is irrelevant: TOML belongs in user Home directory only.
Closes #533
> docs: TOML file belongs in Home dir only

- lib/install.go
- lib/param_parsing/environment.go
- lib/param_parsing/environment_test.go
- lib/param_parsing/parameters.go
- lib/param_parsing/parameters_test.go
- lib/param_parsing/toml.go
- main.go
- test-data/integration-tests/test_tfswitchtoml/.tfswitch.toml
- www/docs/usage/commandline.md
Fixes #318
Note: code in changed files is auto-formatted
Caveats:
- Supports overriding arch via env var and TOML config
- Doesn't override if binary had already been downloaded before
- Remove existing binary from `tfswitch` download dir manually (see `--install` option)
- Spits out Warn log message if requested arch doesn't match actual
- Doesn't check arch value validity and just passes it to download function directly, which will fail if download file doesn't exist on remote
Usage example: `tfswitch --arch arm64 1.10.0`
OpenTofu (for completeness):
> feat: Allow to download binary with custom CPU arch

- CHANGELOG.md
- feat: Allow to download binary with custom CPU arch [#532](https://github.com/warrensbox/terraform-switcher/pull/532) ([yermulnik](https://github.com/yermulnik))
- fix(Makefile): bring up to date [#535](https://github.com/warrensbox/terraform-switcher/pull/535) ([yermulnik](https://github.com/yermulnik))
- fix: Exclude CHANGELOG howto from distribution archives [#528](https://github.com/warrensbox/terraform-switcher/pull/528) ([yermulnik](https://github.com/yermulnik))
- docs: Update CHANGELOG with `v1.3.0` [#539](https://github.com/warrensbox/terraform-switcher/pull/539) ([yermulnik](https://github.com/yermulnik))
- docs: TOML file belongs in Home dir only [#534](https://github.com/warrensbox/terraform-switcher/pull/534) ([yermulnik](https://github.com/yermulnik))
- docs: Update …
> docs: Update CHANGELOG with `v1.3.0`

- lib/checksum.go
- lib/download.go
- lib/files.go
- lib/install.go
- lib/list_versions.go
- lib/param_parsing/parameters.go
- lib/param_parsing/versiontf_test.go
- lib/semver.go
- lib/symlink.go
- lib/utils.go
- main.go
* Drop trailing full stops in messages for consistency
* Capitalize messages
* Use tab instead of space to indent multiline messages
* `InstallProductVersion()`:
* Drop pointless usage message
* Improve error message by expanding word `args` to `Argument`
* Use `product.GetName()` instead of hardcoded `terraform`
* Quit early when `--help` cmdline flag is supplied
* `PrintInvalidTFVersion()` print at Warn log level instead of Info
* `PrintInvalidMinorTFVersion()` print at Warn log level instead of Info
* `UsageMessage()` drop pointless blank lines and extraneous howto
* Code autoformatting in changed files (`golint`)
> feat: Improve messaging

- CHANGELOG.md
[Full Changelog](https://github.com/warrensbox/terraform-switcher/compare/v1.4.1...v1.4.2)
- fix: Improve logging and fix symlink installation issues [#559](https://github.com/warrensbox/terraform-switcher/pull/559) ([yermulnik](https://github.com/yermulnik))
- docs: Update CHANGELOG with `v1.4.2` [#565](https://github.com/warrensbox/terraform-switcher/pull/565) ([yermulnik](https://github.com/yermulnik))
> docs: Update CHANGELOG with `v1.4.2`

- .changelog.yml
- CHANGELOG.howto.md
- lib/param_parsing/parameters_test.go
- lib/param_parsing/toml.go
- lib/param_parsing/toml_test.go
- test-data/integration-tests/test_tfswitchtoml/.tfswitch.toml
* Reinstate historical behavior on Env var expansion for `bin` TOML key, which was inadvertently dropped in #566
* Add the same feature for `install` TOML key
* Update corresponding tests
> fix: reinstate env var expansion in `bin` and add the same for `install` TOML params

- .goreleaser.yml
Since recent change in Goreleaser, it sort of incorrectly crops SHA from changelog entries and we end up with a colon before each entry title. Update Goreleaser `changelog.format` value by dropping `{{ .SHA }}: ` altogether to try abd recity this issue.
> chore: Fix release changelog entry format

- lib/download.go
- lib/download_test.go
- lib/logging.go
- lib/param_parsing/parameters.go
- lib/product.go
- lib/product_test.go
- Add https://keybase.io/hashicorp/pgp_keys.asc as fallback source of Hashicorp's public PGP-key
- Allow multiple sources for Product's public PGP-key
- (unrelated) Preserve ordering of `LogLevels` in output messages to make clear the order of increasing level of verbosity (try to improve UX)
Relates to:
- #540
- #621
> feat: Add KeyBase as fallback source of Hashicorp's public PGP-key

- CHANGELOG.md
- feat: Add KeyBase as fallback source of Hashicorp's public PGP-key [#624](https://github.com/warrensbox/terraform-switcher/pull/624) ([yermulnik](https://github.com/yermulnik))
- fix: [release workflow] `mkdocs gh-deploy` requires creds to persist [#623](https://github.com/warrensbox/terraform-switcher/pull/623) ([yermulnik](https://github.com/yermulnik))
- docs: Update CHANGELOG with `v1.6.0` [#625](https://github.com/warrensbox/terraform-switcher/pull/625) ([yermulnik](https://github.com/yermulnik))
> docs: Update CHANGELOG with `v1.6.0`
