.travis.yml
Makefile
main.go

added option to see version

---

.goreleaser.yml

It is replacing original terraforms installation

rm conflict from terraform

---

lib/symlink.go
main.go

Merging bug fix to master relates to #11

Merging bug fix to master relates to #11 

---

.circleci/config.yml

Adding test for numerous OS during component testing

Adding test for numerous OS during component testing

---

lib/install.go
lib/list_tf_version.go
main.go

added modules to make contribution of code easier

---

.circleci/config.yml

Added as placeholder

---

docs/_config.yml

For future external website use

added vendor directory

---

lib/install.go

Great project!  This PR fixes a small spelling mistake.

Fix a spelling mistake :yellow_heart:

---

lib/common_test.go
lib/download_test.go
lib/files.go

Fixes a small typo which has high visibility when using this tool.

Replace 'teraform' with 'terraform'

---

main.go

Support reading required version from TF code.

---

README.md
main.go

https://github.com/warrensbox/terraform-switcher/issues/120

RE: Take explicit version given to CLI as highest priority

---

README.md
main.go

Add support for reading terragrunt.hcl file.

Support for terragrunt files

---

lib/install.go
vendor/golang.org/x/sys/unix/mkall.sh

Fixes https://github.com/warrensbox/terraform-switcher/issues/152

temp fix for macos on arm64 due to M1 chip

---

.gitignore
go.mod
lib/common_test.go
lib/download_test.go
lib/files_test.go
lib/install.go
lib/install_test.go
main.go

Windows OS fixes
- installation paths
- tests

Windows compatibility changes

---

README.md
main.go

These options can be useful for automations that just need to check
what the latest version is before proceeding.
Also added to the README and cleaned up some typos and whitespace there a bit.

Add "show" options to just show the latest versions rather than actually switch or install.

---

.circleci/config.yml
test-data/test_tfswitchtoml/.tfswitch.toml

Testing PR's with CircleCI would reduce the amount of manual review needed. 
Please take a look at https://circleci.com/docs/2.0/oss/ and considering enabling this.

Automate binary tests from test-data directory

---

.circleci/config.yml

Fix working directory after revert of #232

Upgrade to Golang 1.18

---

main.go

Bringing this change in from the .14 branch: https://github.com/warrensbox/terraform-switcher/pull/240

Fix chdirpath for absolute paths

---

main.go

Fix binPath when getting latest

---

lib/list_versions.go

Trying to solve https://github.com/warrensbox/terraform-switcher/issues/311

Make leading slash optional in regex when looking for versions

---

.github/workflows/release.yml
.goreleaser.yml

fix: Attempt to fix PR335

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yml

Fixes issues related to  install.sh - #339

---

.github/workflows/release.yml
.goreleaser.yml

This is will require more testing but on the branch itself

Test pipeline - automating release

---

.github/workflows/build.yml
.github/workflows/release.yml
.goreleaser.yml

Downgrade ubuntu version

---

.github/workflows/release.yml

test the output for PR

---

.github/workflows/release.yml

I am commenting out the part that is failing.

removing git merge to push release

---

.github/workflows/release.yml
CHANGELOG.md

Issues with log file
update release date

Update release date

---

lib/download_test.go
lib/param_parsing/parameters_test.go
lib/param_parsing/terraform_version_test.go
lib/param_parsing/tfswitch_test.go
lib/param_parsing/toml_test.go

- fixing issues from goreport
See: https://goreportcard.com/report/github.com/warrensbox/terraform-switcher

Fixing Goreport Issues

---

lib/param_parsing/parameters.go

- reinitialize the logger in case the log-level config is changed by a config file.

Log-Level Fix for file-config

---

lib/install.go
lib/symlink.go

Allow use of `bin` keyword in toml config file

Fix user bin path on windows

---

Makefile

Bring it up to date (need to deprecate it in future though)

fix(Makefile): bring up to date

---

lib/install.go
lib/list_versions.go
lib/semver.go
lib/symlink.go

Do not print helper message to add bin directory to `$PATH` when it is already on the `$PATH`.

feat: recommend updating `$PATH` only when necessary

---

.goreleaser.yml

chore(goreleaser): Brews: install Bash completion script

---

Makefile
lib/list_versions.go
lib/list_versions_test.go
lib/param_parsing/parameters.go
lib/semver.go

fix: Commad-line flags to show/install latest stable versions are broken
